export type AttendanceStatus =
  | "present"
  | "late"
  | "absent"
  | "leave"
  | "early-leave"
  | "missing-checkout"
  | "pending-correction";

export const statusMeta: Record<
  AttendanceStatus,
  { label: string; dot: string; badge: string }
> = {
  present: {
    label: "Present",
    dot: "bg-success",
    badge: "bg-success-soft text-success",
  },
  late: { label: "Late", dot: "bg-warning", badge: "bg-warning-soft text-warning" },
  absent: { label: "Absent", dot: "bg-danger", badge: "bg-danger-soft text-danger" },
  leave: { label: "On Leave", dot: "bg-info", badge: "bg-info-soft text-info" },
  "early-leave": {
    label: "Early Leave",
    dot: "bg-violet",
    badge: "bg-violet-soft text-violet",
  },
  "missing-checkout": {
    label: "Missing Check-out",
    dot: "bg-neutral-strong",
    badge: "bg-secondary text-secondary-foreground",
  },
  "pending-correction": {
    label: "Pending Correction",
    dot: "bg-warning",
    badge: "bg-warning-soft text-warning",
  },
};

export type Employee = {
  id: string;
  code: string;
  name: string;
  department: string;
  position: string;
  location: string;
  active: boolean;
  today: AttendanceStatus;
  email: string;
  phone: string;
  shift: string;
  joined: string;
  manager: string;
  type: string;
  nationalId?: string;
  nationalIdExpiry?: string;
  avatar?: string;
  gender?: "male" | "female";
};

const rawEmployees: Employee[] = [
  {
    id: "1",
    code: "EMP001",
    name: "Ahmed Ali",
    department: "IT",
    position: "Software Developer",
    location: "Cairo HQ",
    active: true,
    today: "present",
    email: "ahmed.ali@company.com",
    phone: "+20 100 111 2233",
    shift: "Morning Shift",
    joined: "12 Jan 2023",
    manager: "Khaled Nabil",
    type: "Full-time",
    nationalId: "29408150102345",
    nationalIdExpiry: "14 Aug 2031",
  },
  {
    id: "2",
    code: "EMP002",
    name: "Sara Hassan",
    department: "HR",
    position: "HR Officer",
    location: "Cairo HQ",
    active: true,
    today: "late",
    email: "sara.hassan@company.com",
    phone: "+20 100 222 3344",
    shift: "Morning Shift",
    joined: "03 Mar 2022",
    manager: "Habiba Rahim",
    type: "Full-time",
    nationalId: "29605120109876",
    nationalIdExpiry: "22 May 2030",
  },
  {
    id: "3",
    code: "EMP003",
    name: "Omar Khaled",
    department: "Finance",
    position: "Accountant",
    location: "Giza Office",
    active: true,
    today: "absent",
    email: "omar.khaled@company.com",
    phone: "+20 100 333 4455",
    shift: "Morning Shift",
    joined: "21 Sep 2021",
    manager: "Hany Samir",
    type: "Full-time",
  },
  {
    id: "4",
    code: "EMP004",
    name: "Habiba Rahim",
    department: "HR",
    position: "HR Manager",
    location: "Cairo HQ",
    active: true,
    today: "present",
    email: "HabibaRahim@attend360.com",
    phone: "+20 100 741 9344",
    shift: "Morning Shift",
    joined: "08 Feb 2020",
    manager: "—",
    type: "Full-time",
  },
  {
    id: "5",
    code: "EMP005",
    name: "Youssef Ibrahim",
    department: "Operations",
    position: "Shift Supervisor",
    location: "Alexandria Office",
    active: true,
    today: "leave",
    email: "youssef.ibrahim@company.com",
    phone: "+20 100 555 6677",
    shift: "Evening Shift",
    joined: "15 Jun 2023",
    manager: "Hany Samir",
    type: "Full-time",
  },
  {
    id: "6",
    code: "EMP006",
    name: "Nour Mostafa",
    department: "Marketing",
    position: "Content Specialist",
    location: "Cairo HQ",
    active: true,
    today: "early-leave",
    email: "nour.mostafa@company.com",
    phone: "+20 100 666 7788",
    shift: "Flexible Shift",
    joined: "02 Nov 2024",
    manager: "Habiba Rahim",
    type: "Part-time",
  },
  {
    id: "7",
    code: "EMP007",
    name: "Mohamed Hassan",
    department: "IT",
    position: "QA Engineer",
    location: "Giza Office",
    active: true,
    today: "missing-checkout",
    email: "mohamed.hassan@company.com",
    phone: "+20 100 777 8899",
    shift: "Night Shift",
    joined: "19 Apr 2024",
    manager: "Khaled Nabil",
    type: "Full-time",
  },
  {
    id: "8",
    code: "EMP008",
    name: "Laila Fouad",
    department: "Finance",
    position: "Payroll Officer",
    location: "Cairo HQ",
    active: false,
    today: "absent",
    email: "laila.fouad@company.com",
    phone: "+20 100 888 9900",
    shift: "Morning Shift",
    joined: "27 Jul 2019",
    manager: "Hany Samir",
    type: "Contract",
  },
  {
    id: "9",
    code: "EMP009",
    name: "Tariq Mansour",
    department: "IT",
    position: "DevOps Engineer",
    location: "Cairo HQ",
    active: true,
    today: "present",
    email: "tariq.mansour@company.com",
    phone: "+20 100 999 1122",
    shift: "Morning Shift",
    joined: "14 Jan 2024",
    manager: "Khaled Nabil",
    type: "Full-time",
    nationalId: "29503120104567",
    nationalIdExpiry: "12 Oct 2032",
  },
  {
    id: "10",
    code: "EMP010",
    name: "Reem Al-Ghamdi",
    department: "HR",
    position: "Talent Acquisition Lead",
    location: "Giza Office",
    active: true,
    today: "present",
    email: "reem.ghamdi@company.com",
    phone: "+20 100 123 4567",
    shift: "Morning Shift",
    joined: "05 Jun 2022",
    manager: "Habiba Rahim",
    type: "Full-time",
  },
  {
    id: "11",
    code: "EMP011",
    name: "Karim Adel",
    department: "Operations",
    position: "Logistics Coordinator",
    location: "Alexandria Office",
    active: true,
    today: "late",
    email: "karim.adel@company.com",
    phone: "+20 100 234 5678",
    shift: "Morning Shift",
    joined: "18 Sep 2023",
    manager: "Hany Samir",
    type: "Full-time",
  },
  {
    id: "12",
    code: "EMP012",
    name: "Dina Samy",
    department: "Marketing",
    position: "SEO Specialist",
    location: "Cairo HQ",
    active: true,
    today: "present",
    email: "dina.samy@company.com",
    phone: "+20 100 345 6789",
    shift: "Flexible Shift",
    joined: "11 Feb 2023",
    manager: "Habiba Rahim",
    type: "Full-time",
  },
  {
    id: "13",
    code: "EMP013",
    name: "Khaled Nabil",
    department: "IT",
    position: "Engineering Director",
    location: "Cairo HQ",
    active: true,
    today: "present",
    email: "khaled.nabil@company.com",
    phone: "+20 100 456 7890",
    shift: "Morning Shift",
    joined: "01 Jan 2018",
    manager: "—",
    type: "Full-time",
  },
  {
    id: "14",
    code: "EMP014",
    name: "Hany Samir",
    department: "Finance",
    position: "Finance Director",
    location: "Cairo HQ",
    active: true,
    today: "present",
    email: "hany.samir@company.com",
    phone: "+20 100 567 8901",
    shift: "Morning Shift",
    joined: "15 Apr 2017",
    manager: "—",
    type: "Full-time",
  },
  {
    id: "15",
    code: "EMP015",
    name: "Mariam Zaher",
    department: "Operations",
    position: "Fleet Operations Specialist",
    location: "Giza Office",
    active: true,
    today: "early-leave",
    email: "mariam.zaher@company.com",
    phone: "+20 100 678 9012",
    shift: "Evening Shift",
    joined: "22 Aug 2024",
    manager: "Hany Samir",
    type: "Full-time",
  },
  {
    id: "16",
    code: "EMP016",
    name: "Sherif Osman",
    department: "IT",
    position: "Frontend Engineer",
    location: "Alexandria Office",
    active: true,
    today: "present",
    email: "sherif.osman@company.com",
    phone: "+20 100 789 0123",
    shift: "Morning Shift",
    joined: "10 Mar 2023",
    manager: "Khaled Nabil",
    type: "Full-time",
  },
  {
    id: "17",
    code: "EMP017",
    name: "Yasmin Lotfy",
    department: "HR",
    position: "HR Generalist",
    location: "Cairo HQ",
    active: true,
    today: "leave",
    email: "yasmin.lotfy@company.com",
    phone: "+20 100 890 1234",
    shift: "Morning Shift",
    joined: "07 Dec 2021",
    manager: "Habiba Rahim",
    type: "Full-time",
  },
  {
    id: "18",
    code: "EMP018",
    name: "Tamer Hosny",
    department: "Marketing",
    position: "Brand Designer",
    location: "Giza Office",
    active: true,
    today: "present",
    email: "tamer.hosny@company.com",
    phone: "+20 100 901 2345",
    shift: "Flexible Shift",
    joined: "14 May 2022",
    manager: "Habiba Rahim",
    type: "Full-time",
  },
  {
    id: "19",
    code: "EMP019",
    name: "Rania Bakr",
    department: "Finance",
    position: "Senior Auditor",
    location: "Cairo HQ",
    active: true,
    today: "present",
    email: "rania.bakr@company.com",
    phone: "+20 100 012 3456",
    shift: "Morning Shift",
    joined: "30 Oct 2020",
    manager: "Hany Samir",
    type: "Full-time",
  },
  {
    id: "20",
    code: "EMP020",
    name: "Ziad Tarek",
    department: "IT",
    position: "Backend Developer",
    location: "Alexandria Office",
    active: true,
    today: "present",
    email: "ziad.tarek@company.com",
    phone: "+20 100 123 9988",
    shift: "Morning Shift",
    joined: "01 Feb 2024",
    manager: "Khaled Nabil",
    type: "Full-time",
  },
  {
    id: "21",
    code: "EMP021",
    name: "Salma Fawzy",
    department: "HR",
    position: "People Experience Partner",
    location: "Cairo HQ",
    active: true,
    today: "late",
    email: "salma.fawzy@company.com",
    phone: "+20 100 234 8877",
    shift: "Morning Shift",
    joined: "19 Nov 2023",
    manager: "Habiba Rahim",
    type: "Full-time",
  },
  {
    id: "22",
    code: "EMP022",
    name: "Mostafa Kamel",
    department: "Operations",
    position: "Warehouse Supervisor",
    location: "Alexandria Office",
    active: false,
    today: "absent",
    email: "mostafa.kamel@company.com",
    phone: "+20 100 345 7766",
    shift: "Morning Shift",
    joined: "12 Aug 2019",
    manager: "Hany Samir",
    type: "Contract",
  },
  {
    id: "23",
    code: "EMP023",
    name: "Heba Mahmoud",
    department: "Marketing",
    position: "Social Media Strategist",
    location: "Cairo HQ",
    active: true,
    today: "present",
    email: "heba.mahmoud@company.com",
    phone: "+20 100 456 6655",
    shift: "Flexible Shift",
    joined: "04 Jun 2024",
    manager: "Habiba Rahim",
    type: "Part-time",
  },
  {
    id: "24",
    code: "EMP024",
    name: "Amr Diab",
    department: "IT",
    position: "Cloud Architect",
    location: "Giza Office",
    active: true,
    today: "present",
    email: "amr.diab@company.com",
    phone: "+20 100 567 5544",
    shift: "Morning Shift",
    joined: "23 Jan 2021",
    manager: "Khaled Nabil",
    type: "Full-time",
  },
  {
    id: "25",
    code: "EMP025",
    name: "Farida Shawky",
    department: "Finance",
    position: "Billing Specialist",
    location: "Cairo HQ",
    active: true,
    today: "present",
    email: "farida.shawky@company.com",
    phone: "+20 100 678 4433",
    shift: "Morning Shift",
    joined: "16 Jul 2022",
    manager: "Hany Samir",
    type: "Full-time",
  },
  {
    id: "26",
    code: "EMP026",
    name: "Bassem Youssef",
    department: "Operations",
    position: "Inventory Analyst",
    location: "Giza Office",
    active: true,
    today: "missing-checkout",
    email: "bassem.youssef@company.com",
    phone: "+20 100 789 3322",
    shift: "Night Shift",
    joined: "09 Sep 2023",
    manager: "Hany Samir",
    type: "Full-time",
  },
  {
    id: "27",
    code: "EMP027",
    name: "Inas El-Sayed",
    department: "HR",
    position: "Compensation Analyst",
    location: "Cairo HQ",
    active: true,
    today: "present",
    email: "inas.elsayed@company.com",
    phone: "+20 100 890 2211",
    shift: "Morning Shift",
    joined: "14 Feb 2020",
    manager: "Habiba Rahim",
    type: "Full-time",
  },
  {
    id: "28",
    code: "EMP028",
    name: "Walid Soliman",
    department: "IT",
    position: "Cybersecurity Analyst",
    location: "Alexandria Office",
    active: true,
    today: "present",
    email: "walid.soliman@company.com",
    phone: "+20 100 901 1100",
    shift: "Morning Shift",
    joined: "28 Mar 2022",
    manager: "Khaled Nabil",
    type: "Full-time",
  },
  {
    id: "29",
    code: "EMP029",
    name: "Nadia Hamdy",
    department: "Marketing",
    position: "Copywriter & Communications",
    location: "Giza Office",
    active: true,
    today: "leave",
    email: "nadia.hamdy@company.com",
    phone: "+20 100 012 9911",
    shift: "Flexible Shift",
    joined: "17 May 2023",
    manager: "Habiba Rahim",
    type: "Part-time",
  },
  {
    id: "30",
    code: "EMP030",
    name: "Mahmoud Reda",
    department: "Finance",
    position: "Tax Consultant",
    location: "Cairo HQ",
    active: true,
    today: "present",
    email: "mahmoud.reda@company.com",
    phone: "+20 100 123 8822",
    shift: "Morning Shift",
    joined: "05 Aug 2021",
    manager: "Hany Samir",
    type: "Full-time",
  },
  {
    id: "31",
    code: "EMP031",
    name: "Abeer Sabry",
    department: "Operations",
    position: "QA Inspector",
    location: "Alexandria Office",
    active: true,
    today: "present",
    email: "abeer.sabry@company.com",
    phone: "+20 100 234 7733",
    shift: "Morning Shift",
    joined: "11 Oct 2023",
    manager: "Hany Samir",
    type: "Full-time",
  },
  {
    id: "32",
    code: "EMP032",
    name: "Essam Farouk",
    department: "IT",
    position: "Database Administrator",
    location: "Cairo HQ",
    active: true,
    today: "present",
    email: "essam.farouk@company.com",
    phone: "+20 100 345 6644",
    shift: "Morning Shift",
    joined: "18 Jun 2020",
    manager: "Khaled Nabil",
    type: "Full-time",
  },
];

const femaleNames = new Set([
  "sara hassan",
  "mona adel",
  "habiba rahim",
  "nour mostafa",
  "laila fouad",
  "reem al-ghamdi",
  "dina samy",
  "mariam zaher",
  "yasmin lotfy",
  "rania bakr",
  "salma fawzy",
  "heba mahmoud",
  "farida shawky",
  "inas el-sayed",
  "nadia hamdy",
  "abeer sabry",
  "laila samir",
]);

export function getAvatarByName(name: string, code?: string): string {
  const isFemale = femaleNames.has((name || "").trim().toLowerCase());
  const hash = Math.abs(
    (code || name || "1").split("").reduce((acc, char) => acc + char.charCodeAt(0), 0)
  );
  const idx = (hash % 3) + 1;
  return `/avatars/${isFemale ? "female" : "male"}-${idx}.jpg`;
}

export const employees: Employee[] = rawEmployees.map((e) => ({
  ...e,
  gender: femaleNames.has(e.name.trim().toLowerCase()) ? ("female" as const) : ("male" as const),
  avatar: getAvatarByName(e.name, e.code),
}));

export type AttendanceRecord = {
  id: string;
  employee: string;
  code: string;
  date: string;
  checkIn: string | null;
  checkOut: string | null;
  hours: string;
  status: AttendanceStatus;
  location: string;
  device: string;
  scheduled: string;
  source: string;
};

export const attendanceRecords: AttendanceRecord[] = [
  {
    id: "a1",
    employee: "Ahmed Ali",
    code: "EMP001",
    date: "05 Sep 2026",
    checkIn: "08:55 AM",
    checkOut: "05:05 PM",
    hours: "8h 10m",
    status: "present",
    location: "Cairo HQ",
    device: "PC-001",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Web",
  },
  {
    id: "a2",
    employee: "Sara Hassan",
    code: "EMP002",
    date: "05 Sep 2026",
    checkIn: "09:27 AM",
    checkOut: null,
    hours: "7h 33m",
    status: "late",
    location: "Cairo HQ",
    device: "Mobile-114",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Mobile",
  },
  {
    id: "a3",
    employee: "Omar Khaled",
    code: "EMP003",
    date: "05 Sep 2026",
    checkIn: null,
    checkOut: null,
    hours: "—",
    status: "absent",
    location: "Giza Office",
    device: "—",
    scheduled: "09:00 AM – 05:00 PM",
    source: "—",
  },
  {
    id: "a4",
    employee: "Habiba Rahim",
    code: "EMP004",
    date: "05 Sep 2026",
    checkIn: "08:41 AM",
    checkOut: "05:22 PM",
    hours: "8h 41m",
    status: "present",
    location: "Cairo HQ",
    device: "PC-014",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Device",
  },
  {
    id: "a5",
    employee: "Nour Mostafa",
    code: "EMP006",
    date: "05 Sep 2026",
    checkIn: "09:02 AM",
    checkOut: "03:40 PM",
    hours: "6h 38m",
    status: "early-leave",
    location: "Cairo HQ",
    device: "Mobile-207",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Mobile",
  },
  {
    id: "a6",
    employee: "Mohamed Hassan",
    code: "EMP007",
    date: "05 Sep 2026",
    checkIn: "09:37 PM",
    checkOut: null,
    hours: "—",
    status: "missing-checkout",
    location: "Giza Office",
    device: "PC-052",
    scheduled: "10:00 PM – 06:00 AM",
    source: "Device",
  },
  {
    id: "a7",
    employee: "Youssef Ibrahim",
    code: "EMP005",
    date: "04 Sep 2026",
    checkIn: null,
    checkOut: null,
    hours: "—",
    status: "leave",
    location: "Alexandria Office",
    device: "—",
    scheduled: "02:00 PM – 10:00 PM",
    source: "—",
  },
  {
    id: "a8",
    employee: "Laila Fouad",
    code: "EMP008",
    date: "04 Sep 2026",
    checkIn: null,
    checkOut: null,
    hours: "—",
    status: "absent",
    location: "Cairo HQ",
    device: "—",
    scheduled: "09:00 AM – 05:00 PM",
    source: "—",
  },
  {
    id: "a9",
    employee: "Tariq Mansour",
    code: "EMP009",
    date: "04 Sep 2026",
    checkIn: "08:50 AM",
    checkOut: "05:15 PM",
    hours: "8h 25m",
    status: "present",
    location: "Cairo HQ",
    device: "PC-009",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Web",
  },
  {
    id: "a10",
    employee: "Reem Al-Ghamdi",
    code: "EMP010",
    date: "04 Sep 2026",
    checkIn: "08:58 AM",
    checkOut: "05:02 PM",
    hours: "8h 04m",
    status: "present",
    location: "Giza Office",
    device: "PC-010",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Device",
  },
  {
    id: "a11",
    employee: "Karim Adel",
    code: "EMP011",
    date: "04 Sep 2026",
    checkIn: "09:22 AM",
    checkOut: "05:40 PM",
    hours: "8h 18m",
    status: "late",
    location: "Alexandria Office",
    device: "Mobile-111",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Mobile",
  },
  {
    id: "a12",
    employee: "Dina Samy",
    code: "EMP012",
    date: "04 Sep 2026",
    checkIn: "09:05 AM",
    checkOut: "05:10 PM",
    hours: "8h 05m",
    status: "present",
    location: "Cairo HQ",
    device: "Web",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Web",
  },
  {
    id: "a13",
    employee: "Khaled Nabil",
    code: "EMP013",
    date: "03 Sep 2026",
    checkIn: "08:30 AM",
    checkOut: "05:30 PM",
    hours: "9h 00m",
    status: "present",
    location: "Cairo HQ",
    device: "PC-013",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Device",
  },
  {
    id: "a14",
    employee: "Hany Samir",
    code: "EMP014",
    date: "03 Sep 2026",
    checkIn: "08:45 AM",
    checkOut: "05:15 PM",
    hours: "8h 30m",
    status: "present",
    location: "Cairo HQ",
    device: "PC-014",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Device",
  },
  {
    id: "a15",
    employee: "Mariam Zaher",
    code: "EMP015",
    date: "03 Sep 2026",
    checkIn: "01:50 PM",
    checkOut: "08:30 PM",
    hours: "6h 40m",
    status: "early-leave",
    location: "Giza Office",
    device: "Mobile-115",
    scheduled: "02:00 PM – 10:00 PM",
    source: "Mobile",
  },
  {
    id: "a16",
    employee: "Sherif Osman",
    code: "EMP016",
    date: "03 Sep 2026",
    checkIn: "08:52 AM",
    checkOut: "05:08 PM",
    hours: "8h 16m",
    status: "present",
    location: "Alexandria Office",
    device: "PC-016",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Web",
  },
  {
    id: "a17",
    employee: "Yasmin Lotfy",
    code: "EMP017",
    date: "03 Sep 2026",
    checkIn: null,
    checkOut: null,
    hours: "—",
    status: "leave",
    location: "Cairo HQ",
    device: "—",
    scheduled: "09:00 AM – 05:00 PM",
    source: "—",
  },
  {
    id: "a18",
    employee: "Tamer Hosny",
    code: "EMP018",
    date: "03 Sep 2026",
    checkIn: "09:01 AM",
    checkOut: "05:04 PM",
    hours: "8h 03m",
    status: "present",
    location: "Giza Office",
    device: "Web",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Web",
  },
  {
    id: "a19",
    employee: "Rania Bakr",
    code: "EMP019",
    date: "03 Sep 2026",
    checkIn: "08:48 AM",
    checkOut: "05:20 PM",
    hours: "8h 32m",
    status: "present",
    location: "Cairo HQ",
    device: "PC-019",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Device",
  },
  {
    id: "a20",
    employee: "Ziad Tarek",
    code: "EMP020",
    date: "03 Sep 2026",
    checkIn: "08:56 AM",
    checkOut: "05:12 PM",
    hours: "8h 16m",
    status: "present",
    location: "Alexandria Office",
    device: "PC-020",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Web",
  },
  {
    id: "a21",
    employee: "Salma Fawzy",
    code: "EMP021",
    date: "03 Sep 2026",
    checkIn: "09:19 AM",
    checkOut: "05:35 PM",
    hours: "8h 16m",
    status: "late",
    location: "Cairo HQ",
    device: "Mobile-121",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Mobile",
  },
  {
    id: "a22",
    employee: "Mostafa Kamel",
    code: "EMP022",
    date: "03 Sep 2026",
    checkIn: null,
    checkOut: null,
    hours: "—",
    status: "absent",
    location: "Alexandria Office",
    device: "—",
    scheduled: "09:00 AM – 05:00 PM",
    source: "—",
  },
  {
    id: "a23",
    employee: "Heba Mahmoud",
    code: "EMP023",
    date: "03 Sep 2026",
    checkIn: "09:04 AM",
    checkOut: "04:30 PM",
    hours: "7h 26m",
    status: "present",
    location: "Cairo HQ",
    device: "Web",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Web",
  },
  {
    id: "a24",
    employee: "Amr Diab",
    code: "EMP024",
    date: "03 Sep 2026",
    checkIn: "08:35 AM",
    checkOut: "05:05 PM",
    hours: "8h 30m",
    status: "present",
    location: "Giza Office",
    device: "PC-024",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Device",
  },
  {
    id: "a25",
    employee: "Farida Shawky",
    code: "EMP025",
    date: "03 Sep 2026",
    checkIn: "08:50 AM",
    checkOut: "05:10 PM",
    hours: "8h 20m",
    status: "present",
    location: "Cairo HQ",
    device: "PC-025",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Web",
  },
  {
    id: "a26",
    employee: "Bassem Youssef",
    code: "EMP026",
    date: "03 Sep 2026",
    checkIn: "09:45 PM",
    checkOut: null,
    hours: "—",
    status: "missing-checkout",
    location: "Giza Office",
    device: "PC-026",
    scheduled: "10:00 PM – 06:00 AM",
    source: "Device",
  },
  {
    id: "a27",
    employee: "Inas El-Sayed",
    code: "EMP027",
    date: "03 Sep 2026",
    checkIn: "08:44 AM",
    checkOut: "05:01 PM",
    hours: "8h 17m",
    status: "present",
    location: "Cairo HQ",
    device: "PC-027",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Web",
  },
  {
    id: "a28",
    employee: "Walid Soliman",
    code: "EMP028",
    date: "03 Sep 2026",
    checkIn: "08:53 AM",
    checkOut: "05:09 PM",
    hours: "8h 16m",
    status: "present",
    location: "Alexandria Office",
    device: "PC-028",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Device",
  },
  {
    id: "a29",
    employee: "Nadia Hamdy",
    code: "EMP029",
    date: "03 Sep 2026",
    checkIn: null,
    checkOut: null,
    hours: "—",
    status: "leave",
    location: "Giza Office",
    device: "—",
    scheduled: "09:00 AM – 05:00 PM",
    source: "—",
  },
  {
    id: "a30",
    employee: "Mahmoud Reda",
    code: "EMP030",
    date: "03 Sep 2026",
    checkIn: "08:49 AM",
    checkOut: "05:14 PM",
    hours: "8h 25m",
    status: "present",
    location: "Cairo HQ",
    device: "PC-030",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Web",
  },
  {
    id: "a31",
    employee: "Abeer Sabry",
    code: "EMP031",
    date: "03 Sep 2026",
    checkIn: "08:57 AM",
    checkOut: "05:03 PM",
    hours: "8h 06m",
    status: "present",
    location: "Alexandria Office",
    device: "PC-031",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Device",
  },
  {
    id: "a32",
    employee: "Essam Farouk",
    code: "EMP032",
    date: "03 Sep 2026",
    checkIn: "08:40 AM",
    checkOut: "05:00 PM",
    hours: "8h 20m",
    status: "present",
    location: "Cairo HQ",
    device: "PC-032",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Web",
  },
  {
    id: "a33",
    employee: "Ahmed Ali",
    code: "EMP001",
    date: "02 Sep 2026",
    checkIn: "08:52 AM",
    checkOut: "05:02 PM",
    hours: "8h 10m",
    status: "present",
    location: "Cairo HQ",
    device: "PC-001",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Web",
  },
  {
    id: "a34",
    employee: "Sara Hassan",
    code: "EMP002",
    date: "02 Sep 2026",
    checkIn: "08:59 AM",
    checkOut: "05:10 PM",
    hours: "8h 11m",
    status: "present",
    location: "Cairo HQ",
    device: "Mobile-114",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Mobile",
  },
  {
    id: "a35",
    employee: "Omar Khaled",
    code: "EMP003",
    date: "28 Aug 2026",
    checkIn: "09:20 AM",
    checkOut: "05:25 PM",
    hours: "8h 05m",
    status: "late",
    location: "Giza Office",
    device: "PC-003",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Device",
  },
  {
    id: "a36",
    employee: "Habiba Rahim",
    code: "EMP004",
    date: "28 Aug 2026",
    checkIn: "08:35 AM",
    checkOut: "05:15 PM",
    hours: "8h 40m",
    status: "present",
    location: "Cairo HQ",
    device: "PC-014",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Device",
  },
  {
    id: "a37",
    employee: "Nour Mostafa",
    code: "EMP006",
    date: "28 Aug 2026",
    checkIn: "09:00 AM",
    checkOut: "05:00 PM",
    hours: "8h 00m",
    status: "present",
    location: "Cairo HQ",
    device: "Mobile-207",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Mobile",
  },
  {
    id: "a38",
    employee: "Mohamed Hassan",
    code: "EMP007",
    date: "28 Aug 2026",
    checkIn: "09:55 PM",
    checkOut: "06:05 AM",
    hours: "8h 10m",
    status: "present",
    location: "Giza Office",
    device: "PC-052",
    scheduled: "10:00 PM – 06:00 AM",
    source: "Device",
  },
  {
    id: "a39",
    employee: "Tariq Mansour",
    code: "EMP009",
    date: "28 Aug 2026",
    checkIn: "08:48 AM",
    checkOut: "05:10 PM",
    hours: "8h 22m",
    status: "present",
    location: "Cairo HQ",
    device: "PC-009",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Web",
  },
  {
    id: "a40",
    employee: "Karim Adel",
    code: "EMP011",
    date: "28 Aug 2026",
    checkIn: "08:55 AM",
    checkOut: "05:05 PM",
    hours: "8h 10m",
    status: "present",
    location: "Alexandria Office",
    device: "Mobile-111",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Mobile",
  },
  {
    id: "a41",
    employee: "Mariam Zaher",
    code: "EMP015",
    date: "28 Aug 2026",
    checkIn: "01:58 PM",
    checkOut: "10:05 PM",
    hours: "8h 07m",
    status: "present",
    location: "Giza Office",
    device: "Mobile-115",
    scheduled: "02:00 PM – 10:00 PM",
    source: "Mobile",
  },
  {
    id: "a42",
    employee: "Ziad Tarek",
    code: "EMP020",
    date: "28 Aug 2026",
    checkIn: "08:50 AM",
    checkOut: "05:15 PM",
    hours: "8h 25m",
    status: "present",
    location: "Alexandria Office",
    device: "PC-020",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Web",
  },
  {
    id: "a43",
    employee: "Ahmed Ali",
    code: "EMP001",
    date: "25 Aug 2026",
    checkIn: "08:50 AM",
    checkOut: "05:00 PM",
    hours: "8h 10m",
    status: "present",
    location: "Cairo HQ",
    device: "PC-001",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Web",
  },
  {
    id: "a44",
    employee: "Sara Hassan",
    code: "EMP002",
    date: "25 Aug 2026",
    checkIn: "09:15 AM",
    checkOut: "05:20 PM",
    hours: "8h 05m",
    status: "late",
    location: "Cairo HQ",
    device: "Mobile-114",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Mobile",
  },
  {
    id: "a45",
    employee: "Habiba Rahim",
    code: "EMP004",
    date: "25 Aug 2026",
    checkIn: "08:40 AM",
    checkOut: "05:10 PM",
    hours: "8h 30m",
    status: "present",
    location: "Cairo HQ",
    device: "PC-014",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Device",
  },
  {
    id: "a46",
    employee: "Tariq Mansour",
    code: "EMP009",
    date: "25 Aug 2026",
    checkIn: "08:55 AM",
    checkOut: "05:05 PM",
    hours: "8h 10m",
    status: "present",
    location: "Cairo HQ",
    device: "PC-009",
    scheduled: "09:00 AM – 05:00 PM",
    source: "Web",
  },
];

export const activityFeed = [
  {
    name: "Ahmed Mohamed",
    action: "Checked in",
    time: "08:54 AM",
    office: "Cairo HQ",
    status: "present" as AttendanceStatus,
  },
  {
    name: "Sara Ali",
    action: "Checked out",
    time: "05:12 PM",
    office: "Cairo HQ",
    status: "present" as AttendanceStatus,
  },
  {
    name: "Mohamed Hassan",
    action: "Late arrival",
    time: "09:37 AM",
    office: "Giza Office",
    status: "late" as AttendanceStatus,
  },
  {
    name: "Omar Khaled",
    action: "Marked absent",
    time: "10:00 AM",
    office: "Giza Office",
    status: "absent" as AttendanceStatus,
  },
  {
    name: "Nour Mostafa",
    action: "Left early",
    time: "03:40 PM",
    office: "Cairo HQ",
    status: "early-leave" as AttendanceStatus,
  },
];

export type CorrectionRequest = {
  id: string;
  employee: string;
  code: string;
  date: string;
  field: string;
  current: string;
  requested: string;
  reason: string;
  status: "pending" | "approved" | "rejected";
  submitted: string;
};

export const corrections: CorrectionRequest[] = [
  {
    id: "c1",
    employee: "Sara Hassan",
    code: "EMP002",
    date: "03 Sep 2026",
    field: "Check In",
    current: "09:32 AM",
    requested: "09:00 AM",
    reason: "Forgot to check in, was in a client meeting.",
    status: "pending",
    submitted: "09:45 AM",
  },
  {
    id: "c2",
    employee: "Mohamed Hassan",
    code: "EMP007",
    date: "02 Sep 2026",
    field: "Check Out",
    current: "—",
    requested: "06:05 AM",
    reason: "Device offline at end of night shift.",
    status: "pending",
    submitted: "08:12 AM",
  },
  {
    id: "c3",
    employee: "Ahmed Ali",
    code: "EMP001",
    date: "28 Aug 2026",
    field: "Check In",
    current: "09:21 AM",
    requested: "08:58 AM",
    reason: "Badge reader failure at Cairo HQ entrance.",
    status: "approved",
    submitted: "10:02 AM",
  },
  {
    id: "c4",
    employee: "Nour Mostafa",
    code: "EMP006",
    date: "25 Aug 2026",
    field: "Check Out",
    current: "03:40 PM",
    requested: "05:10 PM",
    reason: "Worked from meeting room without device.",
    status: "rejected",
    submitted: "04:31 PM",
  },
];

export const notifications = [
  {
    group: "Today",
    items: [
      { icon: "late", title: "Ahmed arrived late", meta: "09:32 AM · Cairo HQ", type: "late" },
      {
        icon: "correction",
        title: "Sara requested attendance correction",
        meta: "09:45 AM · Check-in 09:32 → 09:00",
        type: "pending-correction",
      },
      { icon: "absent", title: "Omar is absent", meta: "10:00 AM · Giza Office", type: "absent" },
      {
        icon: "device",
        title: "New device registration pending",
        meta: "11:20 AM · Mobile-311 · Nour Mostafa",
        type: "missing-checkout",
      },
    ],
  },
  {
    group: "Yesterday",
    items: [
      {
        icon: "correction",
        title: "Correction approved for Ahmed Ali",
        meta: "Check-in updated to 08:58 AM",
        type: "present",
      },
      {
        icon: "missing",
        title: "Missing check-out — Mohamed Hassan",
        meta: "Night shift 02 Sep",
        type: "missing-checkout",
      },
      { icon: "new", title: "New employee added: Nour Mostafa", meta: "Marketing · Cairo HQ", type: "leave" },
    ],
  },
];

export const devices = [
  {
    id: "PC-001",
    type: "Desktop",
    employee: "Ahmed Ali",
    location: "Cairo HQ",
    registered: "12 Jan 2023",
    lastUsed: "03 Sep 2026 08:55",
    status: "Approved",
  },
  {
    id: "Mobile-114",
    type: "Mobile",
    employee: "Sara Hassan",
    location: "Cairo HQ",
    registered: "04 Mar 2024",
    lastUsed: "03 Sep 2026 09:27",
    status: "Approved",
  },
  {
    id: "Mobile-311",
    type: "Mobile",
    employee: "Nour Mostafa",
    location: "Cairo HQ",
    registered: "03 Sep 2026",
    lastUsed: "—",
    status: "Pending",
  },
  {
    id: "PC-052",
    type: "Kiosk",
    employee: "Shared — Night shift",
    location: "Giza Office",
    registered: "19 Apr 2024",
    lastUsed: "03 Sep 2026 21:37",
    status: "Approved",
  },
  {
    id: "Tablet-007",
    type: "Tablet",
    employee: "Reception",
    location: "Alexandria Office",
    registered: "11 Nov 2022",
    lastUsed: "18 Aug 2026 07:02",
    status: "Blocked",
  },
];

export const locations = [
  { name: "Cairo HQ", address: "12 Nile St, Downtown, Cairo", employees: 164, radius: "150 m" },
  { name: "Giza Office", address: "44 Pyramids Rd, Giza", employees: 58, radius: "120 m" },
  { name: "Alexandria Office", address: "9 Corniche, Alexandria", employees: 26, radius: "100 m" },
];

export const shifts = [
  { name: "Morning Shift", window: "09:00 AM – 05:00 PM", grace: "10 min", employees: 182 },
  { name: "Evening Shift", window: "02:00 PM – 10:00 PM", grace: "10 min", employees: 34 },
  { name: "Night Shift", window: "10:00 PM – 06:00 AM", grace: "15 min", employees: 22 },
  { name: "Flexible Shift", window: "Any 8h between 07:00 – 21:00", grace: "—", employees: 10 },
];

export const permissionMatrix = [
  { permission: "View Employees", admin: "✓", manager: "Team", employee: "Own" },
  { permission: "Add Employee", admin: "✓", manager: "—", employee: "—" },
  { permission: "View Attendance", admin: "✓", manager: "Team", employee: "Own" },
  { permission: "Edit Attendance", admin: "✓", manager: "✓", employee: "—" },
  { permission: "Approve Correction", admin: "✓", manager: "✓", employee: "—" },
  { permission: "Reports", admin: "✓", manager: "Team", employee: "Own" },
  { permission: "Settings", admin: "✓", manager: "—", employee: "—" },
];

export const workSchedule = [
  { day: "Monday", hours: "09:00 – 17:00", weekend: false },
  { day: "Tuesday", hours: "09:00 – 17:00", weekend: false },
  { day: "Wednesday", hours: "09:00 – 17:00", weekend: false },
  { day: "Thursday", hours: "09:00 – 17:00", weekend: false },
  { day: "Friday", hours: "Weekend", weekend: true },
  { day: "Saturday", hours: "Weekend", weekend: true },
  { day: "Sunday", hours: "09:00 – 17:00", weekend: false },
];

/** Day-by-day status map for the employee history calendar (September 2026). */
export const septemberDays: { day: number; status: AttendanceStatus | "weekend" | "future" }[] =
  Array.from({ length: 30 }, (_, i) => {
    const day = i + 1;
    // 4 Sep 2026 is a Friday → Fri/Sat weekends.
    const isWeekend = [4, 5, 11, 12, 18, 19, 25, 26].includes(day);
    if (isWeekend) return { day, status: "weekend" as const };
    if (day > 3) return { day, status: "future" as const };
    if (day === 1) return { day, status: "late" as const };
    if (day === 2) return { day, status: "present" as const };
    return { day, status: "present" as const };
  });

export const lateReport = [
  { employee: "Ahmed Ali", date: "Sep 2", scheduled: "09:00", actual: "09:18", lateBy: "18m" },
  { employee: "Sara Hassan", date: "Sep 3", scheduled: "09:00", actual: "09:32", lateBy: "32m" },
  { employee: "Mohamed Hassan", date: "Sep 3", scheduled: "22:00", actual: "22:37", lateBy: "37m" },
  { employee: "Nour Mostafa", date: "Sep 1", scheduled: "09:00", actual: "09:11", lateBy: "11m" },
];

export const absenceReport = [
  {
    employee: "Omar Khaled",
    date: "Sep 3",
    department: "Finance",
    shift: "Morning",
    type: "Unpaid",
    reason: "No record",
    approved: false,
  },
  {
    employee: "Laila Fouad",
    date: "Sep 2",
    department: "Finance",
    shift: "Morning",
    type: "Sick leave",
    reason: "Medical certificate",
    approved: true,
  },
  {
    employee: "Youssef Ibrahim",
    date: "Sep 3",
    department: "Operations",
    shift: "Evening",
    type: "Annual leave",
    reason: "Planned vacation",
    approved: true,
  },
];

export const attendanceTrend = [
  { day: "Aug 28", present: 205, late: 14, absent: 21 },
  { day: "Aug 31", present: 218, late: 9, absent: 16 },
  { day: "Sep 1", present: 224, late: 11, absent: 13 },
  { day: "Sep 2", present: 210, late: 16, absent: 22 },
  { day: "Sep 3", present: 213, late: 12, absent: 18 },
];
